/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "errors": {
        "tokens": {
            "accessTokenMissing": string;
            "accessTokenVerificationFailed": string;
            "refreshTokenMissing": string;
            "refreshTokenExpiredOrInvalid": string;
        };
        "users": {
            "userDoesNotExist": string;
            "userAlreadyExists": string;
            "loggedOut": string;
            "invalidEmail": string;
            "invalidId": string;
            "invalidUserOrCampgroundId": string;
            "invalidPassword": string;
            "newAndConfirmedPasswordsDoNotMatch": string;
        };
        "reviews": {
            "reviewDoesNotExist": string;
            "invalidReviewOrUserId": string;
            "invalidCampgroundId": string;
            "campgroundDoesNotExist": string;
            "invalidUserId": string;
            "invalidId": string;
            "campgroundRatingUpdateFailed": string;
        };
        "images": {
            "imageDoesNotExist": string;
            "invalidImageOrUserId": string;
            "invalidId": string;
            "invalidCampgroundId": string;
            "invalidImageFormat": string;
            "notAllowedImageFormat": string;
            "imageSizeExceedsLimit": string;
        };
        "campgrounds": {
            "campgroundDoesNotExist": string;
            "invalidId": string;
            "invalidTitle": string;
            "invalidSlug": string;
            "campgroundAlreadyExists": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
