/* DO NOT EDIT, file generated by nestjs-i18n */

 
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "errors": {
        "auth": {
            "tokens": {
                "accessTokenMissing": string;
                "accessTokenVerificationFailed": string;
                "refreshTokenMissing": string;
                "refreshTokenExpiredOrInvalid": string;
            };
            "users": {
                "userDoesNotExist": string;
                "userAlreadyExists": string;
                "loggedOut": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
