import type { Metadata } from 'next';

import '@repo/tailwind-config/styles';
import 'mapbox-gl/dist/mapbox-gl.css';
import { ReactNode } from 'react';
import { nunito } from 'src/app/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className="scroll-p-5 scroll-smooth">
      <body className={`relative bg-neutral-100 ${nunito.variable} font-primary`}>
        <div className="flex min-h-dvh flex-col">{children}</div>
      </body>
    </html>
  );
}
