import type { Metadata } from 'next';

import '@repo/tailwind-config/styles';
import { nunito } from 'app/fonts';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`relative bg-neutral-100 ${nunito.variable} font-primary`}>
        <div className="flex min-h-dvh flex-col">{children}</div>
      </body>
    </html>
  );
}
