export const ACCESS_TOKEN_EXPIRATION_SECONDS = 15 * 60; // 15 minutes
export const ACCESS_TOKEN_EXPIRATION_MILLISECONDS = ACCESS_TOKEN_EXPIRATION_SECONDS * 1000; // 15 minutes
export const REFRESH_TOKEN_EXPIRATION_MILLISECONDS = 7 * 24 * 60 * 60 * 1000; // 7 days
