import type { Metadata } from 'next';

import '@repo/tailwind-config/styles';
import '@/app/styles.css';
import 'mapbox-gl/dist/mapbox-gl.css';
import { ReactNode } from 'react';
import { nunito } from 'src/app/fonts';

import Providers from './_providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale } = await params;

  return (
    <html lang={locale} className="scroll-p-5 scroll-smooth">
      <body className={`relative bg-neutral-100 ${nunito.variable} font-primary`}>
        <Providers>
          <div className="flex min-h-dvh flex-col">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
