export const ACCESS_TOKEN_EXPIRATION_SECONDS = 60 * 15;

export const REFRESH_TOKEN_EXPIRATION_MILLISECONDS = 7 * 24 * 60 * 60 * 1000;
export const REFRESH_TOKEN_EXPIRY_DATE = new Date(Date.now() + REFRESH_TOKEN_EXPIRATION_MILLISECONDS);
