export const MIN_CAMPGROUND_TITLE_LENGTH = 5;
export const MAX_CAMPGROUND_TITLE_LENGTH = 80;

export const CAMPGROUND_SLUG_REGEX = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export const MIN_CAMPGROUND_SLUG_LENGTH = 5;
export const MAX_CAMPGROUND_SLUG_LENGTH = 100;

export const MIN_CAMPGROUND_DESCRIPTION_LENGTH = 30;
export const MAX_CAMPGROUND_DESCRIPTION_LENGTH = 1500;

export const MIN_CAMPGROUND_LOCATION_LENGTH = 3;
export const MAX_CAMPGROUND_LOCATION_LENGTH = 100;

export const MIN_CAMPGROUND_PRICE = 0;
export const MAX_CAMPGROUND_PRICE = 5000;

export const MIN_CAMPGROUND_IMAGES = 0;
export const MAX_CAMPGROUND_IMAGES = 8;
