import type { Metadata } from 'next';

import '@repo/tailwind-config/styles';
import Logo from '@/components/shared/Logo';
import Divider from '@repo/ui/divider';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface AuthLayoutProps {
  children: ReactNode;
}

export default function AuthLayout({ children }: AuthLayoutProps) {
  return (
    <>
      <div className="flex items-center justify-center bg-white py-2.5 lg:py-5">
        <Logo className="text-4xl" />
      </div>
      <Divider />
      <main className="container flex flex-1 flex-col py-10">{children}</main>
    </>
  );
}
